[env:m5stack-atom-m4-2-native]
platform = espressif32@6.12.0
board = m5stack-atom
framework = arduino
monitor_speed = 115200
upload_speed = 46080
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DARDUINO_RUNNING_CORE=0
  -Ilib/azt/include
board_build.filesystem = littlefs
lib_extra_dirs =
  lib
lib_deps =
  bblanchon/ArduinoJson @ ^7.0.0
extra_scripts =
  pre:scripts/build_meta.py
