[env]
platform = espressif32@6.12.0
board = m5stack-atom
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DARDUINO_RUNNING_CORE=0
  -Ilib/azt/include
lib_extra_dirs =
  lib
lib_deps =
  bblanchon/ArduinoJson @ ^7.0.0
extra_scripts =
  pre:scripts/build_meta.py

[env:atom-echo]
board = m5stack-atom
build_src_filter = +<main.cpp> +<azt_https_server.cpp>

[env:atom-echos3r]
board = m5stack-atoms3
board_build.flash_mode = dio
build_src_filter = +<main.cpp> +<azt_https_server.cpp>
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

[env:m5stack-atoms3r-serial-poc]
board = m5stack-atoms3
board_build.flash_mode = dio
build_src_filter = +<serial_poc.cpp>
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

[env:m5stack-atoms3r-wifi-signal-poc]
board = m5stack-atoms3
board_build.flash_mode = dio
build_src_filter = +<wifi_signal_poc.cpp>
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

[env:m5stack-atoms3r-serial-m1]
board = m5stack-atoms3
board_build.flash_mode = dio
build_src_filter = +<serial_matrix_poc.cpp>
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DSERIAL_MODE=1

[env:m5stack-atoms3r-serial-m2]
board = m5stack-atoms3
board_build.flash_mode = dio
build_src_filter = +<serial_matrix_poc.cpp>
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DSERIAL_MODE=2

[env:m5stack-atoms3r-serial-m3]
board = m5stack-atoms3
board_build.flash_mode = dio
build_src_filter = +<serial_matrix_poc.cpp>
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DSERIAL_MODE=3
