from __future__ import annotations

import argparse


def _sort_subcommands_alpha(subparsers_action: argparse._SubParsersAction) -> None:
    subparsers_action.choices = dict(sorted(subparsers_action.choices.items(), key=lambda kv: kv[0]))
    subparsers_action._choices_actions.sort(
        key=lambda a: str(getattr(a, "dest", None) or getattr(a, "metavar", ""))
    )


def build_parser(handlers: argparse.Namespace) -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="azt-tool",
        description=(
            "Unified AZT client CLI.\n\n"
            "Use 'azt-tool <command> --help' for command-specific options."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--config", default="azt.conf", help="Path to local AZT config file (default: ./azt.conf)")
    p.add_argument("--no-config", action="store_true", help="Disable auto-loading defaults from config file")

    sub = p.add_subparsers(dest="command", required=True, metavar="<command>")

    sp = sub.add_parser("sign-config", help="Sign an unsigned AZT config JSON with admin Ed25519 key")
    sp.add_argument("--in", dest="in_path", required=True, help="Path to unsigned config JSON")
    sp.add_argument("--key", dest="key_path", required=False, default="", help="Path to admin private key PEM")
    sp.add_argument("--out", dest="out_path", required=True, help="Output path for signed config JSON")
    sp.add_argument("--fingerprint", dest="fingerprint", default="", help="Optional signer fingerprint override")
    sp.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    sp.set_defaults(func=handlers.cmd_sign_config)

    sa = sub.add_parser("apply-config", help="Sign unsigned config and apply directly to device")
    sa.add_argument("--host", default="", help="Device host/IP")
    sa.add_argument("--port", type=int, default=8080, help="Device API port")
    sa.add_argument("--in", dest="in_path", default="", help="Unsigned config JSON path")
    sa.add_argument("--key", dest="key_path", default="", help="Admin private key PEM")
    sa.add_argument("--fingerprint", dest="fingerprint", default="", help="Optional signer fingerprint override")
    sa.add_argument("--timeout", type=int, default=15, help="HTTP timeout seconds")
    sa.add_argument("--interactive", action="store_true", help="Prompt for missing values using [default] prompts")
    sa.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    sa.set_defaults(func=handlers.cmd_apply_config)

    spatch = sub.add_parser("config-patch", help="Sign and apply /api/v0/config/patch payload")
    spatch.add_argument("--host", default="", help="Device host/IP")
    spatch.add_argument("--port", type=int, default=8080, help="Device API port")
    spatch.add_argument("--patch", dest="patch_path", default="", help="Patch object JSON path (merged with CLI flags)")
    spatch.add_argument("--device-label", default="", help="Set patch.device_label")
    spatch.add_argument("--wifi-ssid", default="", help="Set patch.wifi.ssid")
    spatch.add_argument("--wifi-pass", default="", help="Set patch.wifi.pass")
    spatch.add_argument("--wifi-mode", choices=["sta", "ap"], default="", help="Set patch.wifi.mode")
    spatch.add_argument("--wifi-ap-ssid", default="", help="Set patch.wifi.ap_ssid")
    spatch.add_argument("--wifi-ap-password", default="", help="Set patch.wifi.ap_password")
    spatch.add_argument("--authorized-listener-ip", dest="authorized_listener_ips", action="append", default=[], help="Append patch.authorized_listener_ips entry (repeatable)")
    spatch.add_argument("--time-server", dest="time_servers", action="append", default=[], help="Append patch.time server entry (repeatable)")
    spatch.add_argument("--recording-key-pem", default="", help="Set patch.recording_key.public_key_pem from PEM file path")
    spatch.add_argument("--audio-preamp-gain", type=int, default=None, help="Set patch.audio.preamp_gain (1..8)")
    spatch.add_argument("--audio-adc-gain", type=int, default=None, help="Set patch.audio.adc_gain (0..255)")
    spatch.add_argument("--mdns-enabled", action="store_true", help="Set patch.mdns.enabled=true")
    spatch.add_argument("--mdns-disabled", action="store_true", help="Set patch.mdns.enabled=false")
    spatch.add_argument("--mdns-hostname", default="", help="Set patch.mdns.hostname")
    spatch.add_argument("--if-version", type=int, default=-1, help="Expected current config_revision (default: auto-detect from state)")
    spatch.add_argument("--key", dest="key_path", default="", help="Admin private key PEM")
    spatch.add_argument("--fingerprint", dest="fingerprint", default="", help="Optional signer fingerprint override")
    spatch.add_argument("--timeout", type=int, default=15, help="HTTP timeout seconds")
    spatch.add_argument("--interactive", action="store_true", help="Prompt for missing values using [default] prompts")
    spatch.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    spatch.set_defaults(func=handlers.cmd_config_patch)

    sv = sub.add_parser("stream-validate", help="Validate AZT1 stream chain (key optional in plaintext next-header mode)")
    sv.add_argument("--in", dest="in_path", required=True, help="Input AZT1 file")
    sv.add_argument("--key", dest="key_path", default="", help="Recorder private key PEM (required only for encrypted next-header mode)")
    sv.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    sv.set_defaults(func=handlers.cmd_stream_validate)

    sd = sub.add_parser("stream-decode", help="Fully validate AZT1 stream and decode PCM to WAV")
    sd.add_argument("--in", dest="in_path", nargs="+", required=True, help="Input AZT1 file(s). Accepts multiple paths (e.g. *.azt)")
    sd.add_argument("--key", dest="key_path", required=True, help="Recorder private key PEM")
    sd.add_argument("--out", dest="out_path", default="", help="Output WAV path (single input only; default: <in>.wav)")
    sd.add_argument("--apply-gain", action="store_true", help="Apply recommended_decode_gain from stream header")
    sd.add_argument("--gain", type=float, default=None, help="Explicit decode gain multiplier (overrides --apply-gain)")
    sd.add_argument("--preserve-tail", action="store_true", help="Keep unsigned tail audio after the last verified checkpoint (default: trim unsigned tail)")
    sd.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    sd.set_defaults(func=handlers.cmd_stream_decode)

    sb = sub.add_parser("ota-bundle-create", help="Create one-file OTA bundle: JSON header line + raw firmware bytes")
    sb.add_argument("--key", dest="key_path", default="", help="Signer private key PEM")
    sb.add_argument("--version", default="", help="Firmware version label (human-readable). Defaults to --version-code when omitted")
    sb.add_argument("--version-code", default="", help="Monotonic numeric version code used for anti-rollback, or 'timestamp' for current UTC YYYYMMDDHHMMSS")
    sb.add_argument("--rollback-floor-code", default="same", help="Minimum allowed version_code after this update, or 'same' (default). Use 0 only if you intentionally allow unrestricted rollback")
    sb.add_argument("--channel", default="main", help="Channel label (default: main)")
    sb.add_argument("--target", required=False, default="", choices=["atom-echo", "atom-echos3r"], help="Target device family for OTA compatibility checks")
    sb.add_argument("--firmware", dest="firmware_path", default="", help="Optional firmware .bin path (if omitted, always rebuild current source)")
    sb.add_argument("--out", dest="out_path", default="", help="Output .otabundle file")
    sb.add_argument("--post", dest="post_upgrade", action="store_true", help="POST bundle to device upgrade endpoint after creation")
    sb.add_argument("--host", default="", help="Device host/IP for --post")
    sb.add_argument("--port", type=int, default=8080, help="Device API port")
    sb.add_argument("--upgrade-path", default="/api/v0/device/upgrade", help="Upgrade endpoint path")
    sb.add_argument("--timeout", type=int, default=45, help="HTTP timeout seconds")
    sb.add_argument("--interactive", action="store_true", help="Prompt for missing values using [default] prompts")
    sb.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    sb.set_defaults(func=handlers.cmd_ota_bundle_create)

    spost = sub.add_parser("ota-bundle-post", help="POST one-file OTA bundle to MCU upgrade endpoint")
    spost.add_argument("--host", default="", help="Device host/IP")
    spost.add_argument("--port", type=int, default=8080, help="Device API port")
    spost.add_argument("--in", dest="in_path", default="", help="Input .otabundle file")
    spost.add_argument("--upgrade-path", default="/api/v0/device/upgrade", help="Upgrade endpoint path")
    spost.add_argument("--timeout", type=int, default=45, help="HTTP timeout seconds")
    spost.add_argument("--interactive", action="store_true", help="Prompt for missing values using [default] prompts")
    spost.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    spost.set_defaults(func=handlers.cmd_ota_bundle_post)

    ssh = sub.add_parser("detached-headers-export", help="Export detached header request package from AZT1")
    ssh.add_argument("--in", dest="in_path", required=True, help="Input AZT1 file")
    ssh.add_argument("--out-headers", default="", help="Output detached request package (default: <in>.request)")
    ssh.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    ssh.set_defaults(func=handlers.cmd_separate_headers)

    sdh = sub.add_parser("detached-headers-decode", help="Decode next header with key from .azt or .azt.request; emit .key and optionally .decoded")
    sdh.add_argument("--in", dest="in_path", required=True, help="Input AZT1 file or detached request (.azt.request)")
    sdh.add_argument("--key", dest="key_path", required=True, help="Recorder private key PEM")
    sdh.add_argument("--out", dest="out_path", default="", help="Output decoded AZT1 file (default: <in>.decoded)")
    sdh.add_argument("--out-key", dest="out_decoded_next_header_path", default="", help="Output detached decoded header bytes (default: <in>.key)")
    sdh.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    sdh.set_defaults(func=handlers.cmd_decode_next_header)

    sch = sub.add_parser("detached-headers-combine", help="Combine AZT1 + detached request + detached key into decoded AZT1")
    sch.add_argument("--in", dest="in_path", required=True, help="Original AZT1 source file")
    sch.add_argument("--in-headers", dest="headers_path", default="", help="Detached request package (default: <in>.request)")
    sch.add_argument("--key-file", dest="decoded_next_header_path", default="", help="Detached decoded header bytes file (default: <in>.key)")
    sch.add_argument("--out", dest="out_path", default="", help="Output decoded AZT1 file (default: <in>.decoded)")
    sch.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    sch.set_defaults(func=handlers.cmd_combine_headers)

    # Back-compat aliases (will be removed later)
    ssh_old = sub.add_parser("separate-headers", help=argparse.SUPPRESS)
    ssh_old.add_argument("--in", dest="in_path", required=True)
    ssh_old.add_argument("--out-headers", default="")
    ssh_old.add_argument("--json", dest="as_json", action="store_true")
    ssh_old.set_defaults(func=handlers.cmd_separate_headers)

    sdh_old = sub.add_parser("decode-next-header", help=argparse.SUPPRESS)
    sdh_old.add_argument("--in", dest="in_path", required=True)
    sdh_old.add_argument("--key", dest="key_path", required=True)
    sdh_old.add_argument("--out", dest="out_path", default="")
    sdh_old.add_argument("--out-decoded-next-header", dest="out_decoded_next_header_path", default="")
    sdh_old.add_argument("--json", dest="as_json", action="store_true")
    sdh_old.set_defaults(func=handlers.cmd_decode_next_header)

    sch_old = sub.add_parser("combine-headers", help=argparse.SUPPRESS)
    sch_old.add_argument("--in", dest="in_path", required=True)
    sch_old.add_argument("--in-headers", dest="headers_path", default="")
    sch_old.add_argument("--decoded-next-header", dest="decoded_next_header_path", default="")
    sch_old.add_argument("--out", dest="out_path", default="")
    sch_old.add_argument("--json", dest="as_json", action="store_true")
    sch_old.set_defaults(func=handlers.cmd_combine_headers)

    sc = sub.add_parser("certify-issue", help="Create signed issue certification artifact (mandatory key ownership + nonce attestation verify)")
    sc.add_argument("--host", required=True, help="Device host/IP (mandatory ownership check)")
    sc.add_argument("--port", type=int, default=8080, help="Device API port")
    sc.add_argument("--timeout", type=int, default=15, help="HTTP timeout seconds")
    sc.add_argument("--serial", required=True, help="Device serial number")
    sc.add_argument("--issue-id", required=True, help="Issue identifier")
    sc.add_argument("--title", required=True, help="Issue title")
    sc.add_argument("--expected", default="", help="Expected behavior")
    sc.add_argument("--actual", default="", help="Actual behavior")
    sc.add_argument("--repro", action="append", default=[], help="Repro step (repeatable)")
    sc.add_argument("--evidence", action="append", default=[], help="Evidence path or note (repeatable)")
    sc.add_argument("--meta", action="append", default=[], help="Additional metadata key=value (repeatable)")
    sc.add_argument("--nonce", default="", help="Optional nonce hex (auto-generated if omitted)")
    sc.add_argument("--cert-serial", default="", help="Device certificate serial to upload (defaults to --issue-id)")
    sc.add_argument("--no-upload-device-cert", action="store_true", help="Skip uploading device certificate to /api/v0/device/certificate")
    sc.add_argument("--key", dest="key_path", required=True, help="Signer private key PEM")
    sc.add_argument("--out", dest="out_path", required=True, help="Output certification JSON")
    sc.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    sc.set_defaults(func=handlers.cmd_certify_issue)

    svc = sub.add_parser("verify-certification", help="Verify signed issue certification artifact")
    svc.add_argument("--in", dest="in_path", required=True, help="Certification JSON file")
    svc.add_argument("--key", dest="key_path", required=True, help="Verifier key PEM (public or private)")
    svc.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    svc.set_defaults(func=handlers.cmd_verify_certification)

    spu = sub.add_parser("provision-unit", help="Run full provision_unit workflow")
    spu.add_argument("--port", default=None, help="Serial port (e.g. /dev/ttyUSB0)")
    spu.add_argument("--ip", default=None, help="Device IP fallback")
    spu.add_argument("--baud", type=int, default=None, help="Serial baud for IP autodetect")
    spu.add_argument("--ip-timeout", type=int, default=None, help="Seconds to wait for serial IP autodetect")
    spu.add_argument("--no-auto-ip", action="store_true", help="Disable serial IP autodetect")
    spu.add_argument("--identity", default=None, help="Device identity label")
    spu.add_argument("--wifi-ssid", default=None, help="Wi-Fi SSID")
    spu.add_argument("--wifi-password", default=None, help="Wi-Fi password")
    spu.add_argument("--skip-flash", action="store_true", help="Skip flashing before provisioning")
    spu.add_argument("--artifact-dir", default=None, help="Existing artifact dir to reuse keys")
    spu.add_argument("--allow-serial-bootstrap", action="store_true", help="Allow privileged serial bootstrap if HTTP is unreachable")
    spu.add_argument("passthrough", nargs=argparse.REMAINDER, help="Extra args forwarded to tools.provision_unit")
    spu.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    spu.set_defaults(func=handlers.cmd_provision_unit)

    serase = sub.add_parser("erase-device", help="Erase device flash (NVS/FS/app) for clean-room testing")
    serase.add_argument("--port", default="/dev/ttyUSB0", help="Serial port (e.g. /dev/ttyUSB0)")
    serase.add_argument("--target", required=False, default="", choices=["atom-echo", "atom-echos3r"], help="Hardware target")
    serase.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    serase.set_defaults(func=handlers.cmd_erase_device)

    sflash = sub.add_parser("flash-device", help="Flash firmware to device (source build or OTA bundle)")
    sflash.add_argument("--port", default="/dev/ttyUSB0", help="Serial port (e.g. /dev/ttyUSB0)")
    sflash.add_argument("--target", required=False, default="", choices=["atom-echo", "atom-echos3r"], help="Hardware target")
    sflash.add_argument("--from-source", action="store_true", help="Flash from current source build")
    sflash.add_argument("--from-ota", default="", help="Flash from OTA bundle file (.otabundle)")
    sflash.add_argument("--firmware-key", default="", help="Signer key PEM path (private/public) or raw Ed25519 public-key b64; defaults to embedded dev OTA key")
    sflash.add_argument("--bypass-validation", action="store_true", help="Skip OTA signature/metadata validation checks (unsafe)")
    sflash.add_argument("--apply-ota-state", dest="apply_ota_state", action="store_true", default=True, help="After OTA serial flash, apply OTA signer/version/floor state over serial (default: on)")
    sflash.add_argument("--no-apply-ota-state", dest="apply_ota_state", action="store_false", help="Do not apply OTA signer/version/floor state after OTA serial flash")
    sflash.add_argument("--ota-floor-code", default="", help="Override OTA floor code for serial state apply (default: rollback_floor_code from bundle when present)")
    sflash.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    sflash.set_defaults(func=handlers.cmd_flash_device)

    ssigncred = sub.add_parser("create-signing-credentials", help="Generate Ed25519 signing keypair artifacts")
    ssigncred.add_argument("--identity", default=None, help="Explicit identity label")
    ssigncred.add_argument("--identity-prefix", default="sign", help="Identity prefix when --identity is omitted")
    ssigncred.add_argument("--out-dir", default="", help="Optional output directory (default: client/tools/provisioned/<identity>)")
    ssigncred.add_argument("--password", action="store_true", help="Wrap generated private key with interactive password prompt")
    ssigncred.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    ssigncred.set_defaults(func=handlers.cmd_create_signing_credentials)

    sdeccred = sub.add_parser("create-decoding-credentials", help="Generate RSA decoding keypair artifacts")
    sdeccred.add_argument("--identity", default=None, help="Explicit identity label")
    sdeccred.add_argument("--identity-prefix", default="decode", help="Identity prefix when --identity is omitted")
    sdeccred.add_argument("--out-dir", default="", help="Optional output directory (default: client/tools/provisioned/<identity>)")
    sdeccred.add_argument("--password", action="store_true", help="Wrap generated private key with interactive password prompt")
    sdeccred.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    sdeccred.set_defaults(func=handlers.cmd_create_decoding_credentials)

    sconf = sub.add_parser("configure-device", help="Apply signed config to device using admin/recorder credentials")
    sconf.add_argument("--admin-creds-dir", required=False, default="", help="Path to admin credentials directory")
    sconf.add_argument("--recorder-creds-dir", default="", help="Path to recorder credentials directory (defaults to admin creds)")
    sconf.add_argument("--identity", required=True, help="Device identity label")
    sconf.add_argument("--wifi-ssid", required=False, default="", help="Wi-Fi SSID")
    sconf.add_argument("--wifi-password", required=False, default="", help="Wi-Fi password (STA mode)")
    sconf.add_argument("--wifi-mode", choices=["sta", "ap"], default="sta", help="Wi-Fi mode (sta|ap)")
    sconf.add_argument("--wifi-ap-ssid", required=False, default="", help="Wi-Fi AP SSID (AP mode)")
    sconf.add_argument("--wifi-ap-password", required=False, default="", help="Wi-Fi AP password (AP mode, min 8 chars)")
    sconf.add_argument("--authorized-listener-ip", action="append", default=[], help="Authorized listener IPv4 (repeatable)")
    sconf.add_argument("--time-server", action="append", default=[], help="Time server hostname (repeatable)")
    sconf.add_argument("--no-time", action="store_true", help="Disable external time servers (uses local non-routable placeholder)")
    sconf.add_argument("--port", default="/dev/ttyUSB0", help="Serial port")
    sconf.add_argument("--host", default="", help="Device host/IP for direct Wi-Fi configure path")
    sconf.add_argument("--ip", default="", help="Deprecated alias for --host")
    sconf.add_argument("--baud", type=int, default=115200, help="Serial baud for IP autodetect")
    sconf.add_argument("--ip-timeout", type=int, default=20, help="IP autodetect timeout seconds")
    sconf.add_argument("--no-auto-ip", action="store_true", help="Disable serial IP autodetect")
    sconf.add_argument("--allow-serial-bootstrap", action="store_true", help="Allow privileged serial bootstrap if HTTP is unreachable")
    sconf.add_argument("--mdns-enabled", action="store_true", help="Enable mDNS advertisement")
    sconf.add_argument("--audio-preamp-gain", type=int, default=None, help="Set audio.preamp_gain in bootstrap config (1..8)")
    sconf.add_argument("--audio-adc-gain", type=int, default=None, help="Set audio.adc_gain in bootstrap config (0..255)")
    sconf.add_argument("--mdns-hostname", default="", help="mDNS hostname (without .local); defaults to device label")
    sconf.add_argument("--ota-version-code", default="", help="Current OTA version code for this image (uint64), or 'timestamp' for current UTC YYYYMMDDHHMMSS. Required when using --ota-min-version-code")
    sconf.add_argument("--ota-min-version-code", default="", help="Set OTA rollback floor (uint64) or 'same'. Serial-configurable only")
    sconf.add_argument("--ota-min-version-code-clear", action="store_true", help="Clear OTA rollback floor to 0. Serial-configurable only")
    sconf.add_argument("--ota-signer-public-key-pem", default="", help="Override OTA signer public key PEM from file path (serial-configurable only)")
    sconf.add_argument("--ota-signer-clear", action="store_true", help="Clear OTA signer override (serial-configurable only)")
    sconf.add_argument("--tls-bootstrap", dest="tls_bootstrap", action="store_true", default=True, help="After config, auto-bootstrap TLS if not already configured (default: on)")
    sconf.add_argument("--no-tls-bootstrap", dest="tls_bootstrap", action="store_false", help="Disable automatic TLS bootstrap during configure-device")
    sconf.add_argument("--tls-valid-days", type=int, default=180, help="TLS certificate validity for auto-bootstrap path")
    sconf.add_argument("--tls-reboot-wait-seconds", type=int, default=8, help="Seconds to wait after TLS bootstrap reboot before HTTPS re-check")
    sconf.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    sconf.set_defaults(func=handlers.cmd_configure_device)

    sipd = sub.add_parser("ip-detect", help="Detect device IP from serial output")
    sipd.add_argument("--port", default="/dev/ttyUSB0", help="Serial port")
    sipd.add_argument("--baud", type=int, default=115200, help="Serial baud")
    sipd.add_argument("--timeout", type=int, default=20, help="Detection timeout seconds")
    sipd.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    sipd.set_defaults(func=handlers.cmd_ip_detect)

    smdns = sub.add_parser("mdns-fqdn-get", help="Get device mDNS FQDN")
    smdns.add_argument("--host", required=False, default="", help="Device host/IP")
    smdns.add_argument("--port", type=int, default=8080, help="Device API port")
    smdns.add_argument("--timeout", type=int, default=15, help="HTTP timeout seconds")
    smdns.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    smdns.set_defaults(func=handlers.cmd_mdns_fqdn_get)

    sstate = sub.add_parser("state-get", help="Fetch device config/state endpoint")
    sstate.add_argument("--host", required=False, default="", help="Device host/IP")
    sstate.add_argument("--port", type=int, default=8080, help="Device API port")
    sstate.add_argument("--timeout", type=int, default=15, help="HTTP timeout seconds")
    sstate.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    sstate.set_defaults(func=handlers.cmd_state_get)

    satt = sub.add_parser("attestation-get", help="Fetch device attestation (nonce auto-generated by default)")
    satt.add_argument("--host", required=False, default="", help="Device host/IP")
    satt.add_argument("--nonce", default="", help="Optional test-only nonce override (normally auto-generated; avoid in production)")
    satt.add_argument("--port", type=int, default=8080, help="Device API port")
    satt.add_argument("--timeout", type=int, default=15, help="HTTP timeout seconds")
    satt.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    satt.set_defaults(func=handlers.cmd_attestation_get)

    scertg = sub.add_parser("certificate-get", help="Fetch device certificate")
    scertg.add_argument("--host", required=False, default="", help="Device host/IP")
    scertg.add_argument("--port", type=int, default=8080, help="Device API port")
    scertg.add_argument("--timeout", type=int, default=15, help="HTTP timeout seconds")
    scertg.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    scertg.set_defaults(func=handlers.cmd_certificate_get)

    scerti = sub.add_parser("certificate-issue", help="Issue signed device certificate document")
    scerti.add_argument("--host", required=False, default="", help="Device host/IP")
    scerti.add_argument("--key", dest="key_path", required=False, default="", help="Admin signer private key PEM")
    scerti.add_argument("--attestation", dest="attestation_path", default="", help="Optional verified attestation artifact JSON path (if omitted, attestation is verified automatically)")
    scerti.add_argument("--attestation-max-age-s", type=int, default=120, help="Maximum allowed attestation age in seconds")
    scerti.add_argument("--cert-serial", required=True, help="Certificate serial")
    scerti.add_argument("--out", dest="out_path", default="", help="Optional output JSON path")
    scerti.add_argument("--valid-until-utc", default="2036-01-01T00:00:00Z")
    scerti.add_argument("--auto-record", action="store_true", help="Authorize recorder auto-record consumer in certificate")
    scerti.add_argument("--auto-decode", action="store_true", help="Authorize air-gap auto-decode consumer in certificate")
    scerti.add_argument("--port", type=int, default=8080, help="Device API port")
    scerti.add_argument("--timeout", type=int, default=15, help="HTTP timeout seconds")
    scerti.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    scerti.set_defaults(func=handlers.cmd_certificate_issue)

    scertp = sub.add_parser("certificate-post", help="Upload device certificate")
    scertp.add_argument("--host", required=False, default="", help="Device host/IP")
    scertp.add_argument("--in", dest="in_path", required=True, help="Certificate JSON path")
    scertp.add_argument("--port", type=int, default=8080, help="Device API port")
    scertp.add_argument("--timeout", type=int, default=15, help="HTTP timeout seconds")
    scertp.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    scertp.set_defaults(func=handlers.cmd_certificate_post)

    screvoke = sub.add_parser("certificate-revoke", help="Revoke device certificate using signed nonce challenge")
    screvoke.add_argument("--host", required=False, default="", help="Device host/IP")
    screvoke.add_argument("--key", dest="key_path", required=False, default="", help="Admin signer private key PEM")
    screvoke.add_argument("--cert-serial", default="", help="Certificate serial to revoke (defaults to device active serial)")
    screvoke.add_argument("--port", type=int, default=8080, help="Device API port")
    screvoke.add_argument("--timeout", type=int, default=15, help="HTTP timeout seconds")
    screvoke.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    screvoke.set_defaults(func=handlers.cmd_certificate_revoke)

    skeym = sub.add_parser("key-match-check", help="Check admin key fingerprint matches device state")
    skeym.add_argument("--host", required=False, default="", help="Device host/IP")
    skeym.add_argument("--key", dest="key_path", required=False, default="", help="Admin private key PEM")
    skeym.add_argument("--port", type=int, default=8080, help="Device API port")
    skeym.add_argument("--timeout", type=int, default=15, help="HTTP timeout seconds")
    skeym.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    skeym.set_defaults(func=handlers.cmd_key_match_check)

    sreboot = sub.add_parser("reboot-device", help="Trigger authenticated device reboot")
    sreboot.add_argument("--host", required=False, default="", help="Device host/IP")
    sreboot.add_argument("--key", dest="key_path", required=False, default="", help="Admin Ed25519 private key PEM for reboot auth challenge signing")
    sreboot.add_argument("--port", type=int, default=8080, help="Device API port")
    sreboot.add_argument("--timeout", type=int, default=15, help="HTTP timeout seconds")
    sreboot.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    sreboot.set_defaults(func=handlers.cmd_reboot_device)

    ssign = sub.add_parser("signing-key-check", help="Verify signing key endpoints consistency")
    ssign.add_argument("--host", required=False, default="", help="Device host/IP")
    ssign.add_argument("--port", type=int, default=8080, help="Device API port")
    ssign.add_argument("--timeout", type=int, default=10, help="HTTP timeout seconds")
    ssign.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    ssign.set_defaults(func=handlers.cmd_signing_key_check)

    sattv = sub.add_parser("attestation-verify", help="Fetch and verify device attestation cryptographically")
    sattv.add_argument("--host", required=False, default="", help="Device host/IP")
    sattv.add_argument("--nonce", default="", help="Optional test-only nonce override (normally auto-generated; avoid in production)")
    sattv.add_argument("--port", type=int, default=8080, help="Device API port")
    sattv.add_argument("--out", dest="out_path", default="", help="Optional output path for verified attestation artifact JSON")
    sattv.add_argument("--timeout", type=int, default=15, help="HTTP timeout seconds")
    sattv.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    sattv.set_defaults(func=handlers.cmd_attestation_verify)

    sredir = sub.add_parser("stream-redirect-check", help="Check stream endpoint returns expected redirect")
    sredir.add_argument("--host", required=False, default="", help="Device host/IP")
    sredir.add_argument("--port", type=int, default=8080, help="Device API port")
    sredir.add_argument("--seconds", type=int, default=1, help="Requested stream duration")
    sredir.add_argument("--stream-port", type=int, default=8081, help="Expected stream redirect port")
    sredir.add_argument("--timeout", type=int, default=10, help="HTTP timeout seconds")
    sredir.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    sredir.set_defaults(func=handlers.cmd_stream_redirect_check)

    sprobe = sub.add_parser(
        "stream-read",
        help="Read stream data; require either --out (save AZT file) or --probe (bytes-only)",
    )
    sprobe.add_argument("--host", required=False, default="", help="Device host/IP")
    sprobe.add_argument("--port", type=int, default=8080, help="Device API port")
    sprobe.add_argument("--seconds", type=float, default=None, help="Optional read duration seconds; omit to run indefinitely")
    sprobe.add_argument("--out", dest="out_path", default="", help="Output AZT file path")
    sprobe.add_argument("--probe", action="store_true", help="Probe mode: do not save file, only report bytes")
    sprobe.add_argument("--timeout", type=int, default=10, help="HTTP timeout seconds")
    sprobe.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    sprobe.set_defaults(func=handlers.cmd_stream_probe, command_name="stream-read")

    stls_init = sub.add_parser("tls-ca-init", help="Initialize local TLS CA (auto-generates if missing)")
    stls_init.add_argument("--common-name", default="Audio-Zero-Trust Local CA", help="CA certificate common name")
    stls_init.add_argument("--force", action="store_true", help="Regenerate CA even if one already exists")
    stls_init.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    stls_init.set_defaults(func=handlers.cmd_tls_ca_init)

    stls_export = sub.add_parser("tls-ca-export", help="Export active TLS CA public certificate")
    stls_export.add_argument("--out", dest="out_path", required=True, help="Output PEM path")
    stls_export.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    stls_export.set_defaults(func=handlers.cmd_tls_ca_export)

    stls_import = sub.add_parser("tls-ca-import", help="Import trusted TLS CA public certificate (verify-only mode)")
    stls_import.add_argument("--in", dest="in_path", required=True, help="Input PEM path")
    stls_import.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    stls_import.set_defaults(func=handlers.cmd_tls_ca_import)

    stls_status = sub.add_parser("tls-ca-status", help="Show local TLS CA material status")
    stls_status.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    stls_status.set_defaults(func=handlers.cmd_tls_ca_status)

    stls_issue = sub.add_parser("tls-cert-issue", help="Issue/install device TLS server certificate from local CA")
    stls_issue.add_argument("--host", required=False, default="", help="Device host/IP")
    stls_issue.add_argument("--key", dest="key_path", required=False, default="", help="Admin Ed25519 private key PEM")
    stls_issue.add_argument("--cert-serial", default="", help="TLS certificate serial (optional; auto-generated if omitted)")
    stls_issue.add_argument("--valid-days", type=int, default=180, help="Issued TLS certificate validity in days")
    stls_issue.add_argument("--port", type=int, default=8080, help="Device API port")
    stls_issue.add_argument("--timeout", type=int, default=15, help="HTTP timeout seconds")
    stls_issue.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    stls_issue.set_defaults(func=handlers.cmd_tls_cert_issue)

    stls_state = sub.add_parser("tls-status", help="Fetch device TLS enrollment status")
    stls_state.add_argument("--host", required=False, default="", help="Device host/IP")
    stls_state.add_argument("--port", type=int, default=8080, help="Device API port")
    stls_state.add_argument("--timeout", type=int, default=15, help="HTTP timeout seconds")
    stls_state.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    stls_state.set_defaults(func=handlers.cmd_tls_status)

    stls_boot = sub.add_parser("tls-bootstrap", help="One-command TLS bootstrap (CA + issue + install + HTTPS verify)")
    stls_boot.add_argument("--host", required=False, default="", help="Device host/IP")
    stls_boot.add_argument("--key", dest="key_path", required=False, default="", help="Admin Ed25519 private key PEM")
    stls_boot.add_argument("--cert-serial", default="", help="TLS certificate serial (optional; auto-generated if omitted)")
    stls_boot.add_argument("--valid-days", type=int, default=180, help="Issued TLS certificate validity in days")
    stls_boot.add_argument("--port", type=int, default=8080, help="Device bootstrap API port (HTTP)")
    stls_boot.add_argument("--https-port", type=int, default=8443, help="Device TLS API port")
    stls_boot.add_argument("--timeout", type=int, default=15, help="HTTP timeout seconds")
    stls_boot.add_argument("--ca-key", dest="ca_key_path", default="", help="Optional CA private key PEM (defaults to local client/tools/pki/ca_private_key.pem)")
    stls_boot.add_argument("--ca-cert", dest="ca_cert_path", default="", help="Optional CA cert PEM (defaults to local client/tools/pki/ca_cert.pem)")
    stls_boot.add_argument("--no-reboot", action="store_true", help="Do not attempt reboot if HTTPS verification initially fails")
    stls_boot.add_argument("--reboot-wait-seconds", type=int, default=8, help="Seconds to wait after reboot before HTTPS re-check")
    stls_boot.add_argument("--json", dest="as_json", action="store_true", help="Emit machine-readable JSON envelope")
    stls_boot.set_defaults(func=handlers.cmd_tls_bootstrap)

    _sort_subcommands_alpha(sub)
    return p
