services:
  azt-listener:
    build: .
    image: azt-listener:dev
    container_name: azt-listener-dev
    restart: unless-stopped
    user: "1000:1000"
    network_mode: host
    command: ["--config", "/config/listener.yaml"]
    environment:
      - TZ=America/Vancouver
    volumes:
      - ./config:/config:ro
      - ./data/recordings:/data/recordings
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
